travis:
  secure:
    BINSTAR_TOKEN: oiUfGgg3tLfZMnO21k/tIS/DCcrDITMnA2qmuLj2JqgQgP7fa2gAeEdKOHZxFV6TKSOHLM3gpukmxkGBzx/++kRQL1L0D9AvETXqP8Uo1224oz2wftfEMOs59wRYI1ZMNm7J/J8HirefwhID71O6U7WHMgTjXujUjWHaQyhhKQUdlGKrjVt8859Td/asz/vrZPe9aE/SmlhZRhJoGI0H2f83il6LuAuDtFBh3sgIF4IDeCnxs14ZOdmjpFDQkmucBCnQoY/vTXcwIuyNxKfioOscsvvyD9iaGHj3PXPfn3gbGsE2BNCnq+RFqLQztDh7YX8/ABy+CfThWjpXS1/MJ4c+kZsPeGdenlQ+CWmtvuYlh+SfaDciisp4siy9KEcBVspuS6N6T15Av87KhrrITFh6KMjrHobh9W5hajRofWrv/vZKiCGRXnRnyOhOZPa7fXZ3F/gXpO5eTHyCAlQkKjqiBcaegbfvWgpLmhfpAVoZpCf/16ApCSCC2T3VJnIUMHGAwpCS2eL8tJ9tD6nBtc6X7keHwKVHuWIi487ECV72I7nrhwjAu3J4BiJ+VpyGP4Nx6bMW+cVIXV8j6j0BNA0/y7H1JylreFBzJwVK8UEMK3bw7vGr+5Gj2F0iHLgRRl1KKkmTJsm0deh24BHea/Ku8WEPl485jviea10OdbE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
