travis:
  secure:
    BINSTAR_TOKEN: E9kQB33o/Yh9p70G214MDil5xo5HFEi+yMftrOHgiiWMGPe0luDZ0cC+t85+LOIvsmVuEkg1+t9mwBUFfqzoVY+fBCa7KsOcWaojutQMXIqxdPaGUtl8So5hb9tznp2YPNTCXDfTd0BV0pPeQhUVIx3EDf/eA4CyUHyA8jKi3BigpvPj3InNP9Z/2mDnC7nis2FnexwaCE99cW5Nq2NnLoCo+jcLSXFCE5+lDprNNZHfKGbARhVoLbiN4+36YTnAiv14bFmAYUynG138gpWeYi5VlQHittiQOussU/c0ISH7aLPabb754CsytU889HiItJ5Kpd4dxA7DfEqUKSIavZrpTHshUVlZDqgBxh0zcv1eieDVj5npwNxCmhCYTGg2ZSJ38dmMjRRLWp01Q4+l8Y9EmmpXeK9kwVOJZ3Dy6+uiSYbXeDIIvVLy6B5Wyq77lZczGC2vRIXPtbLGyR6C31I7wtT/W9nz3bSrxEvdofjloS3iO9pnK0XSezcL7dZ/ffMmouwbT3zSRL4+x1XeEVmYCCEGOADNFxe4yiUlChGmEuoubpDGGjQwHvldgHSz0VE/ZE1ORs88nYVpUWL+u4655NfQMi6+Gj9pGY7NKRBGWbjZ51/xvXQTRBQ5ElM4LEEIaAiqPCktBsUGXHOJkfepOmlI3bHi/cr/wVF9Xjk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
