travis:
  secure:
    BINSTAR_TOKEN: kDs3vZKNa3zvpK5t6yAxUvvX0U+gFLsgGoad33zUHRyQBAwzoU0AmWukHe9WSHT9wgf2t0OVf3kDsiAXaV7D4eRbA7MRIBYyFBZBfw5deGD3Ix1dwpHP26be2g6/mCkrpLK3nIiIZLZGQTxVj85K0VTT+shvEOBB6oUfIdMqQ0B57KUb6P7f9qeyfAkJuQmCHREBGVhfDd4A1KFeJDk81CyeOt/78sAbF2AHxoz/FBJd2oHR8ACG0OH2BQhJ5ct4QNBD4wkyhF+MPeOpl2YhBkGPQUNuq2miMJyQXDx2p4fc1UU7CcZprGGzyqS2ldeKBhnbx6UqzATXxs4vYcNZuNV4D2mqzAqrt/gZZV3dV1t+l6HQ3UIGJUYUPUkYBwPhK01/IlXL6gY30hodgtp+OAH2UHALUWpG1Dswp+uTdIL7Tlz1kz+hz6laQt9x8hmuEewVJ07H0qcdSbI47qHkv/+UgmZlYjanj/B+V/0EM+IoASQ/hx8XdUHuVs5SW9oInfj5mJHqSbj8S9Npz8ioR33P6/BEzmfsj7LBBsRatOfxo8HZepS2vlyowypFOFGZHN9w10cLevjROvlgTzlgHDOxFDqFsqNKLovZOhadHyQGHhcB9eDAJQnNCDSNGlbsXQiqULl3NFu6O8CVeeGmxd9LOXcCEcBYgaoGZ+CTZVI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
